---
- name: Build and Push Docker Image
  hosts: localhost
  connection: local
  tasks:
    - name: Log into Docker Registry
      community.docker.docker_login:
        username: "{{ docker_user }}"
        password: "{{ docker_pass }}"

    - name: Build Image from local Dockerfile
      community.docker.docker_image:
        name: "{{ img_name }}"
        tag: "{{ img_tag }}"
        source: build
        build:
          path: "." # Current directory from GitHub checkout
        state: present

    - name: Tag Image as Latest
      community.docker.docker_image:
        name: "{{ img_name }}"
        repository: "{{ img_name }}:latest"
        source: local

    - name: Push Images to DockerHub
      community.docker.docker_image:
        name: "{{ img_name }}"
        tag: "{{ item }}"
        push: yes
        source: local
      loop:
        - "{{ img_tag }}"
        - "latest"

