---
- name: Build and Push Docker Image on Remote Worker
  hosts: docker_workers
  become: true
  vars:
    # These will be passed from the Jenkinsfile
    repo_name: "{{ docker_repo }}"
    image_tag: "{{ tag }}"
    docker_user: "{{ d_user }}"
    docker_pass: "{{ d_pass }}"
    build_dir: "/tmp/docker_build"

  tasks:
    - name: Create build directory on remote node
      file:
        path: "{{ build_dir }}"
        state: directory
        mode: '0755'

    - name: Copy entire project directory to Remote Worker
      copy:
        src: "./"
        dest: "{{ build_dir }}/"

    - name: Build the Docker Image
      community.docker.docker_image:
        name: "{{ repo_name }}"
        tag: "{{ image_tag }}"
        source: build
        build:
          path: "{{ build_dir }}"
        state: present

    - name: Log into Docker Hub
      community.docker.docker_login:
        username: "{{ docker_user }}"
        password: "{{ docker_pass }}"

    - name: Push Image to Docker Hub
      community.docker.docker_image:
        name: "{{ repo_name }}"
        tag: "{{ image_tag }}"
        push: yes
        source: local

   # - name: Cleanup build directory
    #  file:
       # path: "{{ build_dir }}"
    #    state: absent

