---
- name: Deploy Application to Managed Node
  hosts: all
  become: yes
  tasks:
    - name: Ensure Docker service is active
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    - name: Pull fresh image from DockerHub
      community.docker.docker_image:
        name: "{{ img_name }}"
        tag: "{{ img_tag }}"
        source: pull

    - name: Stop and Remove existing container
      community.docker.docker_container:
        name: my-active-app
        state: absent

    - name: Start the new container
      community.docker.docker_container:
        name: my-active-app
        image: "{{ img_name }}:{{ img_tag }}"
        state: started
        restart_policy: always
        ports:
          - "4000:8080" 

